version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: database-postgres
    environment:
      POSTGRES_DB: shlink_db
      POSTGRES_USER: shlink_user
      POSTGRES_PASSWORD: shlink_pss
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  shlink:
    build: ./
    restart: unless-stopped
    container_name: shlink-backend
    environment:
      DB_DRIVER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: shlink_db
      DB_USER: shlink_user
      DB_PASSWORD: shlink_pss
      DEFAULT_DOMAIN: localhost:8987
      IS_HTTPS_ENABLED: true
      DEFAULT_SHORT_CODES_LENGTH: 8
      DEFAULT_QR_CODE_SIZE: 300
      INITIAL_API_KEY: nekomotsu_secret_api_key
      MULTI_SEGMENT_SLUGS_ENABLED: true
    ports:
      - "8987:8080"
    depends_on:
      - db
  shlink-web-client:
    build: ./shlink-web-client/
    restart: unless-stopped
    container_name: shlink-gui
    environment:
      SHLINK_SERVER_URL: http://localhost:8987
      SHLINK_SERVER_API_KEY: nekomotsu_secret_api_key
    ports:
      - "8081:8080"
    depends_on:
      - shlink
volumes:
  db_data: